source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.4', '>= 6.1.4.4'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# better_errorsとbinding_of_callerを一緒に使うことで、ブラウザ上でエラー確認ができる
gem 'better_errors'
gem 'binding_of_caller'

# Reduces boot times through caching; required in config/boot.rb　rails起動時間の短縮
gem 'bootsnap', '>= 1.4.4', require: false

# bcryptは１、パスワードのハッシュ化を行う。２、ソルトを追加し、ランダムな文字列を入力したパスワードにくっつけて暗号化３、ストレッチングを行い、ハッシュ関数を数千回通して、解読者に嫌がらせを行う。DB追記時にpassword_digestが必要。
gem 'bcrypt', '~> 3.1.7'
# CSRFは掲示板や問い合わせフォームなどを処理するwebアプリケーションが、本来拒否すべき他サイトからのリクエストを受信して処理することで、それを防ぐのがrack-cors
gem 'rack-cors'
gem 'devise', '~> 4.8', '>= 4.8.1'
gem 'devise_token_auth',  '1.1.5'
gem 'devise-i18n',        '1.9.4'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'faker'
  gem 'factory_bot_rails'
  gem 'rubocop'
  gem 'rubocop-rails'
  gem 'rubocop-checkstyle_formatter'
  gem 'rspec-rails'
  gem 'rspec_junit_formatter'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
  gem "rubocop-rspec", require: false
end

group :test do
  gem 'capybara'
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
